### ISSUE TITLE
Spades/Targets

### ISSUE THREAD

**Issue by destanycrane** [bcgov/CCISS#16]

**Comment by CeresBarros** [comment]
We've decided to use `targets`

**Comment by CeresBarros** [comment]
Recent (random) conversations have triggered me into pondering whether SpaDES wouldn't be a better for a CCISS workflow orchestrator. Here are reasons why:
**Documentation**
- SpaDES modules have a clear metadata section embedded in the code - this greatly speeds up and facilitates the creation of metadata and appropriately documenting. It also sort of "forces" us to do it from the start
- each SpaDES module comes with a documentation template `.Rmd` file - again, this speeds up the process of documenting steps of the workflow
- I have created a way to automagically weave together different SpaDES modules' manuals (i.e. `.Rmd` files) into a cohesive manual (see [https://landr-manual.predictiveecology.org/](https://landr-manual.predictiveecology.org/)). These manuals include tables of inputs/outputs that are automatically generated from reading the module's metadata (e.g. [https://landr-manual.predictiveecology.org/landr-biomass_core-module.html#inputs-list](https://landr-manual.predictiveecology.org/landr-biomass_core-module.html#inputs-list)). When a module's inputs/outputs change (or their metadata does) the manual is automatically updated to reflect those changes.

**Building/expanding the BC modelling system in SpaDES**
- other provincial teams have or are adopting SpaDES as the framework to build their models and workflows on. Adding the CCISS workflow to this system can bring benefits to several other teams.

**Comment by CeresBarros** [comment]
After discussing with @cmahony and @kdaust, we have decided to switch to SpaDES.
